"""Add New Fields

Revision ID: f964019aa324
Revises: cbde67399891
Create Date: 2024-05-23 01:58:30.815357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f964019aa324'
down_revision = 'cbde67399891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_column('question')

    # ### end Alembic commands ###
